#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTouristBook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class dealsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_MyTouristbook_Deal(Table_MyTouristbook_Deal instance);
    partial void UpdateTable_MyTouristbook_Deal(Table_MyTouristbook_Deal instance);
    partial void DeleteTable_MyTouristbook_Deal(Table_MyTouristbook_Deal instance);
    #endregion
		
		public dealsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dealsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dealsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dealsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dealsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_MyTouristbook_Deal> Table_MyTouristbook_Deals
		{
			get
			{
				return this.GetTable<Table_MyTouristbook_Deal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_MyTouristbook_Deals")]
	public partial class Table_MyTouristbook_Deal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _owneraid;
		
		private string _ownerusername;
		
		private string _title;
		
		private string _pricing;
		
		private string _description;
		
		private string _dest1;
		
		private string _dealurl;
		
		private string _orderurl;
		
		private string _imageurl;
		
		private System.Nullable<int> _rating;
		
		private System.Nullable<int> _relatedofferid;
		
		private System.Nullable<int> _sponsored;
		
		private System.Nullable<int> _featured;
		
		private System.Nullable<int> _priority;
		
		private System.Nullable<int> _popular;
		
		private string _shortdescription;
		
		private string _country;
		
		private string _city;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnowneraidChanging(System.Nullable<int> value);
    partial void OnowneraidChanged();
    partial void OnownerusernameChanging(string value);
    partial void OnownerusernameChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnpricingChanging(string value);
    partial void OnpricingChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Ondest1Changing(string value);
    partial void Ondest1Changed();
    partial void OndealurlChanging(string value);
    partial void OndealurlChanged();
    partial void OnorderurlChanging(string value);
    partial void OnorderurlChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnratingChanging(System.Nullable<int> value);
    partial void OnratingChanged();
    partial void OnrelatedofferidChanging(System.Nullable<int> value);
    partial void OnrelatedofferidChanged();
    partial void OnsponsoredChanging(System.Nullable<int> value);
    partial void OnsponsoredChanged();
    partial void OnfeaturedChanging(System.Nullable<int> value);
    partial void OnfeaturedChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    partial void OnpopularChanging(System.Nullable<int> value);
    partial void OnpopularChanged();
    partial void OnshortdescriptionChanging(string value);
    partial void OnshortdescriptionChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    #endregion
		
		public Table_MyTouristbook_Deal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owneraid", DbType="Int")]
		public System.Nullable<int> owneraid
		{
			get
			{
				return this._owneraid;
			}
			set
			{
				if ((this._owneraid != value))
				{
					this.OnowneraidChanging(value);
					this.SendPropertyChanging();
					this._owneraid = value;
					this.SendPropertyChanged("owneraid");
					this.OnowneraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerusername", DbType="NVarChar(500)")]
		public string ownerusername
		{
			get
			{
				return this._ownerusername;
			}
			set
			{
				if ((this._ownerusername != value))
				{
					this.OnownerusernameChanging(value);
					this.SendPropertyChanging();
					this._ownerusername = value;
					this.SendPropertyChanged("ownerusername");
					this.OnownerusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1000)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pricing", DbType="NVarChar(4000)")]
		public string pricing
		{
			get
			{
				return this._pricing;
			}
			set
			{
				if ((this._pricing != value))
				{
					this.OnpricingChanging(value);
					this.SendPropertyChanging();
					this._pricing = value;
					this.SendPropertyChanged("pricing");
					this.OnpricingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(4000)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dest1", DbType="NVarChar(400)")]
		public string dest1
		{
			get
			{
				return this._dest1;
			}
			set
			{
				if ((this._dest1 != value))
				{
					this.Ondest1Changing(value);
					this.SendPropertyChanging();
					this._dest1 = value;
					this.SendPropertyChanged("dest1");
					this.Ondest1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dealurl", DbType="NVarChar(1500)")]
		public string dealurl
		{
			get
			{
				return this._dealurl;
			}
			set
			{
				if ((this._dealurl != value))
				{
					this.OndealurlChanging(value);
					this.SendPropertyChanging();
					this._dealurl = value;
					this.SendPropertyChanged("dealurl");
					this.OndealurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderurl", DbType="NVarChar(1500)")]
		public string orderurl
		{
			get
			{
				return this._orderurl;
			}
			set
			{
				if ((this._orderurl != value))
				{
					this.OnorderurlChanging(value);
					this.SendPropertyChanging();
					this._orderurl = value;
					this.SendPropertyChanged("orderurl");
					this.OnorderurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(1500)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="Int")]
		public System.Nullable<int> rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if ((this._rating != value))
				{
					this.OnratingChanging(value);
					this.SendPropertyChanging();
					this._rating = value;
					this.SendPropertyChanged("rating");
					this.OnratingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relatedofferid", DbType="Int")]
		public System.Nullable<int> relatedofferid
		{
			get
			{
				return this._relatedofferid;
			}
			set
			{
				if ((this._relatedofferid != value))
				{
					this.OnrelatedofferidChanging(value);
					this.SendPropertyChanging();
					this._relatedofferid = value;
					this.SendPropertyChanged("relatedofferid");
					this.OnrelatedofferidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sponsored", DbType="Int")]
		public System.Nullable<int> sponsored
		{
			get
			{
				return this._sponsored;
			}
			set
			{
				if ((this._sponsored != value))
				{
					this.OnsponsoredChanging(value);
					this.SendPropertyChanging();
					this._sponsored = value;
					this.SendPropertyChanged("sponsored");
					this.OnsponsoredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_featured", DbType="Int")]
		public System.Nullable<int> featured
		{
			get
			{
				return this._featured;
			}
			set
			{
				if ((this._featured != value))
				{
					this.OnfeaturedChanging(value);
					this.SendPropertyChanging();
					this._featured = value;
					this.SendPropertyChanged("featured");
					this.OnfeaturedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int")]
		public System.Nullable<int> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popular", DbType="Int")]
		public System.Nullable<int> popular
		{
			get
			{
				return this._popular;
			}
			set
			{
				if ((this._popular != value))
				{
					this.OnpopularChanging(value);
					this.SendPropertyChanging();
					this._popular = value;
					this.SendPropertyChanged("popular");
					this.OnpopularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortdescription", DbType="NVarChar(650)")]
		public string shortdescription
		{
			get
			{
				return this._shortdescription;
			}
			set
			{
				if ((this._shortdescription != value))
				{
					this.OnshortdescriptionChanging(value);
					this.SendPropertyChanging();
					this._shortdescription = value;
					this.SendPropertyChanged("shortdescription");
					this.OnshortdescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(500)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
